spring.application.name=auth-service
server.port=8086
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true
spring.datasource.url=jdbc:postgresql://localhost:5432/auth_db
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:Post@29}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
logging.level.com.relivio.auth=INFO
logging.file.name=auth-service.log

auth.seed-admin-password=${AUTH_SEED_ADMIN_PASSWORD:admin123}
auth.seed-volunteer-password=${AUTH_SEED_VOLUNTEER_PASSWORD:vol123}
